### ISSUE TITLE
can't install on ruby2

### ISSUE THREAD

**Issue by mailinglists35** [squish/dnstraverse#1]
it hangs at this step

 gem install -V dnstraverse
HEAD https://api.rubygems.org/api/v1/dependencies
200 OK
GET https://api.rubygems.org/api/v1/dependencies?gems=dnstraverse
200 OK
Getting SRV record failed: DNS result has no information for _rubygems._tcp.api.rubygems.org
GET https://api.rubygems.org/api/v1/dependencies?gems=dnsruby
200 OK
Downloading gem dnstraverse-0.1.14.gem
GET https://api.rubygems.org/gems/dnstraverse-0.1.14.gem
302 Moved Temporarily
GET https://rubygems.global.ssl.fastly.net/gems/dnstraverse-0.1.14.gem
Fetching: dnstraverse-0.1.14.gem (100%)
200 OK
/var/lib/gems/2.3.0/gems/dnstraverse-0.1.14/Rakefile
/var/lib/gems/2.3.0/gems/dnstraverse-0.1.14/bin/dnstraverse
/var/lib/gems/2.3.0/gems/dnstraverse-0.1.14/lib/dnstraverse/caching_resolver.rb
/var/lib/gems/2.3.0/gems/dnstraverse-0.1.14/lib/dnstraverse/decoded_query.rb
/var/lib/gems/2.3.0/gems/dnstraverse-0.1.14/lib/dnstraverse/decoded_query_cache.rb
/var/lib/gems/2.3.0/gems/dnstraverse-0.1.14/lib/dnstraverse/fingerprint.rb
/var/lib/gems/2.3.0/gems/dnstraverse-0.1.14/lib/dnstraverse/fingerprint_rules.rb
/var/lib/gems/2.3.0/gems/dnstraverse-0.1.14/lib/dnstraverse/info_cache.rb
/var/lib/gems/2.3.0/gems/dnstraverse-0.1.14/lib/dnstraverse/log.rb
/var/lib/gems/2.3.0/gems/dnstraverse-0.1.14/lib/dnstraverse/message_utility.rb
/var/lib/gems/2.3.0/gems/dnstraverse-0.1.14/lib/dnstraverse/referral.rb
/var/lib/gems/2.3.0/gems/dnstraverse-0.1.14/lib/dnstraverse/response.rb
/var/lib/gems/2.3.0/gems/dnstraverse-0.1.14/lib/dnstraverse/response_loop.rb
/var/lib/gems/2.3.0/gems/dnstraverse-0.1.14/lib/dnstraverse/response_maxdepth.rb
/var/lib/gems/2.3.0/gems/dnstraverse-0.1.14/lib/dnstraverse/response_noglue.rb
/var/lib/gems/2.3.0/gems/dnstraverse-0.1.14/lib/dnstraverse/summary_stats.rb
/var/lib/gems/2.3.0/gems/dnstraverse-0.1.14/lib/dnstraverse/traverser.rb
/var/lib/gems/2.3.0/gems/dnstraverse-0.1.14/lib/dnstraverse/version.rb
/var/lib/gems/2.3.0/gems/dnstraverse-0.1.14/lib/dnstraverse/x
/var/lib/gems/2.3.0/gems/dnstraverse-0.1.14/test/test_fingerprint.rb
/var/lib/gems/2.3.0/gems/dnstraverse-0.1.14/LICENSE
/var/lib/gems/2.3.0/gems/dnstraverse-0.1.14/README
/usr/local/bin/dnstraverse
Successfully installed dnstraverse-0.1.14
Parsing documentation for dnstraverse-0.1.14
Parsing sources...
100% [19/19]  lib/dnstraverse/x
Installing ri documentation for dnstraverse-0.1.14

^ hang, cpu 100%

on https://github.com/rails/rails/issues/11814 they say it;s something about documentation. can you workaround it?

i've tried installing with --no-rdoc but gives this error when ran:

/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in 'require': cannot load such file -- rdoc/usage (LoadError)
        from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in 'require'
        from /var/lib/gems/2.3.0/gems/dnstraverse-0.1.14/bin/dnstraverse:25:in '<top (required)>'
        from /usr/local/bin/dnstraverse:23:in 'load'
        from /usr/local/bin/dnstraverse:23:in '<main>'

**Comment by rlevitsky** [comment]
I have the same problem. It eats all my CPU and memory during installation, and then refuses to run with

/usr/local/lib/ruby/site_ruby/2.2/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- rdoc/usage (LoadError)
    from /usr/local/lib/ruby/site_ruby/2.2/rubygems/core_ext/kernel_require.rb:55:in`require'
    from /usr/local/lib/ruby/gems/2.2/gems/dnstraverse-0.1.14/bin/dnstraverse:25:in `<top (required)>'
    from /usr/local/bin/dnstraverse:22:in`load'
    from /usr/local/bin/dnstraverse:22:in `<main>'
